version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "npm(backend)"
    labels:
      - "dependencies"
      - "javascript"
      - "backend"
    groups:
      backend-dev-patch:
        dependency-type: "development"
        update-types:
          - "patch"
      backend-dev-minor:
        dependency-type: "development"
        update-types:
          - "minor"
      backend-prod-patch:
        dependency-type: "production"
        update-types:
          - "patch"
      backend-prod-minor:
        dependency-type: "production"
        update-types:
          - "minor"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "npm(frontend)"
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"
    groups:
      frontend-dev-patch:
        dependency-type: "development"
        update-types:
          - "patch"
      frontend-dev-minor:
        dependency-type: "development"
        update-types:
          - "minor"
      frontend-prod-patch:
        dependency-type: "production"
        update-types:
          - "patch"
      frontend-prod-minor:
        dependency-type: "production"
        update-types:
          - "minor"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "docker"
    labels:
      - "dependencies"
      - "docker"
    groups:
      docker-minor-patch:
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      docker-workflow-actions:
        patterns:
          - "docker/*"
          - "actions/checkout"
          - "actions/setup-node"
          - "actions/upload-artifact"
          - "actions/download-artifact"
